export const TESTIMONIAL_DATA = [
  {
    id: 1,
    name: "Albert Jhonson",
    title: "Senior Engineer",
    image: "/assets/design-img/testimonial.png",
    quote: `I am a person who is positive about every aspect of life. There are many things I like to do, to see, and to experience. I like to read, I like to write; I like to think, I like to dream; I like to talk, I like to listen.`,
  },
  {
    id: 2,
    name: "Jeff",
    title: "CTO",
    image: "/assets/design-img/testimonial.png",
    quote: `DXG exceeded our expectations in every aspect. Their Triple E Xperience™ framework truly transformed our event. Engaging elements, seamless networking opportunities, and thought-provoking content showcased their dedication to attendee satisfaction. DXG's adaptability in handling virtual and hybrid formats ensures they remain the top choice for any event production needs.`,
  },
  {
    id: 3,
    name: "Randy",
    title: "CFO",
    image: "/assets/design-img/testimonial.png",
    quote: `DXG's services are a masterpiece in event production. From concept to execution, their team's passion and professionalism shine. The immersive experiences and cutting-edge technology they brought to our event left a lasting impression on attendees. DXG is not just a service provider; they are partners in creating unforgettable moments.`,
  },
];

export const blogData = {
  others: [
    {
      title: "Create a beautiful website for any device.",
      dec: "Demo Digital Xperience Group (DXG), a pioneering division of WLJ Consulting, is a premier partner in transforming events into unforgettable experiences. With our roots firmly planted in the event hospitality industry. We pride ourselves on elevating the digital and production quality of in-person, virtual, and hybrid events.a pioneering division of WLJ Consulting, is a premier partner in transforming events into unforgettable experiences. With our roots firmly.",
      url: "/assets/blogs/blog1.png",
      link: "/",
    },
    {
      title: "Create a beautiful website for any device.",
      dec: "Demo Digital Xperience Group (DXG), a pioneering division of WLJ Consulting, is a premier partner in transforming events into unforgettable experiences. With our roots firmly planted in the event hospitality a pioneering division of WLJ Consulting, is a premier partner in transforming events into unforgettable experiences. With our roots firmly planted in the event hospitality industry.",
      url: "/assets/blogs/blog2.png",
      link: "/",
    },
    {
      title: "Create a beautiful website for any device.",
      dec: "Demo Digital Xperience Group (DXG), a pioneering division of WLJ Consulting, is a premier partner in transforming events into unforgettable experiences. With our roots firmly planted in the event hospitality a pioneering division of WLJ Consulting, is a premier partner in transforming events into unforgettable experiences. With our roots firmly planted in the event hospitality industry.",
      url: "/assets/blogs/blog3.png",
      link: "/",
    },
    {
      title: "Create a beautiful website for any device.",
      dec: "Demo Digital Xperience Group (DXG), a pioneering division of WLJ Consulting, is a premier partner in transforming events into unforgettable experiences. With our roots firmly planted in the event hospitality industry. We pride ourselves on elevating the digital and production quality of in-person, virtual, and hybrid events.a pioneering division of WLJ Consulting, is a premier partner in transforming events into unforgettable experiences. With our roots firmly.",
      url: "/assets/blogs/blog1.png",
      link: "/",
    },
    {
      title: "Create a beautiful website for any device.",
      dec: "Demo Digital Xperience Group (DXG), a pioneering division of WLJ Consulting, is a premier partner in transforming events into unforgettable experiences. With our roots firmly planted in the event hospitality a pioneering division of WLJ Consulting, is a premier partner in transforming events into unforgettable experiences. With our roots firmly planted in the event hospitality industry.",
      url: "/assets/blogs/blog2.png",
      link: "/",
    },
    {
      title: "Create a beautiful website for any device.",
      dec: "Demo Digital Xperience Group (DXG), a pioneering division of WLJ Consulting, is a premier partner in transforming events into unforgettable experiences. With our roots firmly planted in the event hospitality a pioneering division of WLJ Consulting, is a premier partner in transforming events into unforgettable experiences. With our roots firmly planted in the event hospitality industry.",
      url: "/assets/blogs/blog3.png",
      link: "/",
    },
  ],
};

export const portfolioInfo = [
  {
    id: 3,
    cardImage: "assets/portfolio-item/nazara-web.png",
    fullImage: "assets/portfolio-item/nazara-web-full.jpg",
    title: "Nazara",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    category: "Website Design",
    dribbbleLink: "https://dribbble.com/abukawsarux",
    behanceLink: "https://www.behance.net/abukawsarux",
    websiteLink: "https://abukawsarux.vercel.app/",
  },
  {
    id: 3,
    cardImage: "assets/portfolio-item/nazara-web.png",
    fullImage: "assets/portfolio-item/nazara-web-full.jpg",
    title: "Nazara",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    category: "Website Design",
    dribbbleLink: "https://dribbble.com/abukawsarux",
    behanceLink: "https://www.behance.net/abukawsarux",
    websiteLink: "https://abukawsarux.vercel.app/",
  },
  {
    id: 3,
    cardImage: "assets/portfolio-item/nazara-web.png",
    fullImage: "assets/portfolio-item/nazara-web-full.jpg",
    title: "Nazara",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    category: "Website Design",
    dribbbleLink: "https://dribbble.com/abukawsarux",
    behanceLink: "https://www.behance.net/abukawsarux",
    websiteLink: "https://abukawsarux.vercel.app/",
  },
  {
    id: 3,
    cardImage: "assets/portfolio-item/nazara-web.png",
    fullImage: "assets/portfolio-item/nazara-web-full.jpg",
    title: "Nazara",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    category: "Website Design",
    dribbbleLink: "https://dribbble.com/abukawsarux",
    behanceLink: "https://www.behance.net/abukawsarux",
    websiteLink: "https://abukawsarux.vercel.app/",
  },
  {
    id: 3,
    cardImage: "assets/portfolio-item/nazara-web.png",
    fullImage: "assets/portfolio-item/nazara-web-full.jpg",
    title: "Nazara",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    category: "Website Design",
    dribbbleLink: "https://dribbble.com/abukawsarux",
    behanceLink: "https://www.behance.net/abukawsarux",
    websiteLink: "https://abukawsarux.vercel.app/",
  },
  {
    id: 3,
    cardImage: "assets/portfolio-item/nazara-web.png",
    fullImage: "assets/portfolio-item/nazara-web-full.jpg",
    title: "Nazara",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    category: "Website Design",
    dribbbleLink: "https://dribbble.com/abukawsarux",
    behanceLink: "https://www.behance.net/abukawsarux",
    websiteLink: "https://abukawsarux.vercel.app/",
  },
  {
    id: 3,
    cardImage: "assets/portfolio-item/nazara-web.png",
    fullImage: "assets/portfolio-item/nazara-web-full.jpg",
    title: "Nazara",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    category: "Website Design",
    dribbbleLink: "https://dribbble.com/abukawsarux",
    behanceLink: "https://www.behance.net/abukawsarux",
    websiteLink: "https://abukawsarux.vercel.app/",
  },
  {
    id: 3,
    cardImage: "assets/portfolio-item/nazara-web.png",
    fullImage: "assets/portfolio-item/nazara-web-full.jpg",
    title: "Nazara",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. ",
    category: "Website Design",
    dribbbleLink: "https://dribbble.com/abukawsarux",
    behanceLink: "https://www.behance.net/abukawsarux",
    websiteLink: "https://abukawsarux.vercel.app/",
  },
];
